@startuml
class compi1.proyecto1.App
class compi1.proyecto1.Arbol
class compi1.proyecto1.Conjunto
class compi1.proyecto1.CustomOutputStream
class compi1.proyecto1.EstadoAutomata
class compi1.proyecto1.ListaArboles
class compi1.proyecto1.Transicion
class compi1.proyecto1.proyecto1_ventana
class guru.nidi.graphviz.attribute.Label
class guru.nidi.graphviz.engine.Format
class guru.nidi.graphviz.engine.Graphviz
class guru.nidi.graphviz.model.Factory
class guru.nidi.graphviz.model.MutableGraph
class java.awt.Color
class java.awt.EventQueue
class java.awt.Font
class java.awt.Panel
class java.awt.SystemColor
class java.awt.TextArea
class java.awt.event.ActionEvent
class java.awt.event.ActionListener
class java.io.BufferedReader
class java.io.BufferedWriter
class java.io.File
class java.io.FileReader
class java.io.FileWriter
class java.io.IOException
class java.io.OutputStream
class java.io.PrintStream
class java.io.StringReader
class java.time.LocalDateTime
class java.util.ArrayList
class javax.swing.ImageIcon
class javax.swing.JButton
class javax.swing.JFileChooser
class javax.swing.JFrame
class javax.swing.JInternalFrame
class javax.swing.JLabel
class javax.swing.JMenu
class javax.swing.JMenuBar
class javax.swing.JMenuItem
class javax.swing.JPanel
class javax.swing.JScrollBar
class javax.swing.JScrollPane
class javax.swing.JTabbedPane
class javax.swing.JTable
class javax.swing.JTextArea
class javax.swing.JToggleButton
class javax.swing.border.EmptyBorder
class javax.swing.filechooser.FileNameExtensionFilter
class javax.swing.table.DefaultTableModel
@enduml