
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi1.proyecto1;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int PIPE = 15;
  public static final int Llave_C = 3;
  public static final int INTERROGACION = 18;
  public static final int MULTIPLY = 16;
  public static final int Llave_A = 2;
  public static final int PLUS = 17;
  public static final int PCOMMA = 19;
  public static final int CHAR = 11;
  public static final int RCONJ = 7;
  public static final int PAR_C = 13;
  public static final int PAR_A = 12;
  public static final int DQT = 24;
  public static final int ESCDQT = 21;
  public static final int ID = 9;
  public static final int NUM = 10;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CONJ = 4;
  public static final int SQT = 23;
  public static final int NEWLINE = 22;
  public static final int ESCSQT = 20;
  public static final int error = 1;
  public static final int DOT = 14;
  public static final int FLECH = 6;
  public static final int DOBDOT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Llave_A",
  "Llave_C",
  "CONJ",
  "DOBDOT",
  "FLECH",
  "RCONJ",
  "COMMA",
  "ID",
  "NUM",
  "CHAR",
  "PAR_A",
  "PAR_C",
  "DOT",
  "PIPE",
  "MULTIPLY",
  "PLUS",
  "INTERROGACION",
  "PCOMMA",
  "ESCSQT",
  "ESCDQT",
  "NEWLINE",
  "SQT",
  "DQT"
  };
}

